### ISSUE TITLE
Better n body code?

### ISSUE THREAD

**Issue by IanHawke** [shwina/nbody-lesson-draft#3]
In Greg's original challenge this n-body code was taken as a "real, in the wild" code. A lot of comments on the original thread said that the first thing to do would be to rewrite it.

Would it be better to rewrite the n-body code for the purposes of the lesson, to make it simpler to understand and analyze?

**Comment by shwina** [comment]
@IanHawke 

Yes - I'm particularly not very happy with the interface. For instance, we have three representations of the same system:

```
BODIES = {
    'body-1': ([-0.5, 0.0, 0.0], [0.0, 0.0, 0.0], 1),
    'body-2': ([0.5, 0.0, 0.0], [0.0, 0.0, 0.0], 1)
}

SYSTEM = list(BODIES.values())
PAIRS = combinations(SYSTEM)
```

This can get really confusing for both learners and instructors in a workshop. Do you think we can rewrite the code so that the user need only deal with a single representation?

**Comment by IanHawke** [comment]
I think `PAIRS` is redundant. From the numerical point of view it's only `SYSTEM` that is actually used. `BODIES`  has the advantage, for the full solar system, that it's clearer what's going on, but for a single system that could be simply done in a comment, I would have thought.

**Comment by shwina** [comment]
Hmm... Anything else in particular that you think we can improve?

**Comment by IanHawke** [comment]
Separating out the time evolution from the particle-particle interaction would help; that way we would have direct access to the acceleration.

**Comment by shwina** [comment]
Sorry that things have been quiet - I'll be able to work on this this weekend :)

**Comment by shwina** [comment]
@IanHawke 

I've been giving this a lot of thought, and I'm still struggling to think of an interface that will be easy to test for learners that haven't learned about classes in Python. Wondering if you have an idea already?

Ashwin

**Comment by IanHawke** [comment]
Sorry for the delayed response - been away for the bank holiday. I have a
simple idea - will put it up hopefully later today.

**Comment by IanHawke** [comment]
I had less of the code prepared than I thought, and it's very undocumented, but see
https://github.com/IanHawke/nbody-lesson-draft/blob/newcode/code/nbody_new.py

**Comment by shwina** [comment]
@IanHawke - Thanks so much for this; I'll rewrite the tests for this code and see if it looks any better.

**Comment by shwina** [comment]
@IanHawke 

Here are some simple tests rewritten using the new code:
https://github.com/ashwinsrnth/nbody-lesson-draft/blob/gh-pages/code/test_nbody.py

`BODIES` is now a list of tuples (containing lists). Does this look any better?

**Comment by IanHawke** [comment]
Yes, that looks better to me. Thanks!
